config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get '/', to: 'posts#index'
  resource :posts
  resource :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment ,presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :content ,presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    p "8"*100
    # p params
    # p Post.find(params[:format]).comments
    # post_params = params.permit(:title, :content)
    comment_params = params.permit(:comment)
    @comment = Post.find(params[:format]).comments.create(comment_params)
    if @comment.persisted?
      redirect_to action: :show , :controller => :posts , format: params[:format]
    else
      redirect_to action: :show , :controller => :posts , format: params[:format], error: "Comment can't be blank"
    end
  end

  def destroy
    # p "%"*100
    # p params
    @comment = Post.find(params[:post_id]).comments.find(params[:format])
    @comment.delete
    redirect_to action: :show , :controller => :posts , format: params[:post_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = User.find(1).posts.order(updated_at: 'desc')
  end

  def new
    @post = Post.new
  end

  def update
    # p "-"*100
    # p params
    @post = Post.find(params[:format])
    if @post.update(post_params)
      redirect_to action: :index , :controller => :posts
    else
      render :edit
    end
  end

  def edit
    # p params
    @post = Post.find(params[:format])
  end

  def destroy
    @post = Post.find(params[:format])
    @post.delete
    redirect_to action: :index , :controller => :posts
  end

  def show
    @post = User.find(1).posts.find(params[:format])
    @comments = @post.comments
  end

  def create
    # post_params = params.permit(:title, :content)
    @post = User.find(1).posts.create(post_params)
    if @post.persisted?
      redirect_to action: :index , :controller => :posts
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= posts_index_url %>">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= new_posts_url %>">New Post<span class="sr-only">(current)</span></a>
      </li>


    </ul>

  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.erb
<% if @post.errors.any? %>

<div class="alert alert-danger">
  <% @post.errors.full_messages.each do |msg| %>
    <h3><%= msg %></h3>
  <% end %>

</div>
<% end %>
<%= form_for(@post , url: posts_path(@post)) do |f| %>
  <%= f.text_field :title , placeholder: "Title" %>
  <br>
  <br>
  <%= f.text_area :content, rows: "3", placeholder: "Content" %>
  <br>
<!--  <br>-->
  <%#= f.submit "Create" %>
  <%= submit_tag(btn_text,class: "btn btn-#{btn_class}") %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render partial: 'form' , locals: { btn_text: "Update", btn_class: "info"} %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text"><%= post.updated_at %></p>
      <%= link_to 'Show', posts_path(post), method: :get, class: "btn btn-info" %>
      <a href="<%= edit_posts_path(post) %>" class="btn btn-primary">UPDATE</a>
      <%= link_to 'delete', posts_path(post), method: :delete, class: "btn btn-danger" %>

    </div>
  </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<%#= form_tag(posts_url, method: 'post') do %>

  <%#= text_field_tag(:title,"", placeholder: "Title") %>
<!--  <br>-->
<!--  <br>-->
  <%#= text_area_tag(:content,"", rows: "3", placeholder: "Content") %>
<!--  <br>-->
<!--  <br>-->
  <%#= submit_tag("Add New",class: "btn btn-success") %>
<%# end %>

<%= render partial: 'form', locals: { btn_text: "Add New Post", btn_class: "success"} %>

app/views/posts/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-text"><%= @post.content %></p>
    <p class="card-text"><%= @post.updated_at %></p>
    <% if params[:error] %>

      <div class="alert alert-danger">
        <%# flash.each do |name, msg| %>
          <h3><%= params[:error] %></h3>
        <%# end %>

      </div>
    <% end %>
    <%= form_tag(comments_url(@post.id), method: 'post') do %>
      <%= text_area_tag(:comment, "", rows: "3", placeholder: "Content") %>
      <br>
      <br>
      <%= submit_tag("Comment", class: "btn btn-success") %>
    <% end %>
    <% @comments.each do |comment| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= comment.comment %></h5>
         <!-- <p class="card-text"><%#= post.content %></p>
          <%#= link_to 'Show', posts_path(post), method: :get, class: "btn btn-info" %>
          <a href="<%#= edit_posts_path(post) %>" class="btn btn-primary">UPDATE</a>-->
          <%= link_to 'delete', comments_path(comment,post_id: @post.id ), method: :delete, class: "btn btn-danger" %>

        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>
<br>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>